// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0YgvCrlBJqrgob8b_0d89wM9amZt0d24',
    appId: '1:664203654470:web:1ad6c038fc0b5a549d6147',
    messagingSenderId: '664203654470',
    projectId: 'readora-8cc74',
    authDomain: 'readora-8cc74.firebaseapp.com',
    storageBucket: 'readora-8cc74.firebasestorage.app',
    measurementId: 'G-E4Q926WRTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqpXxcc-nlZalhIXWUUXxyketDpWqhTdU',
    appId: '1:664203654470:android:a30a868d6bb8173c9d6147',
    messagingSenderId: '664203654470',
    projectId: 'readora-8cc74',
    storageBucket: 'readora-8cc74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCurgzkegga07FFVVJ3uuTVXvrPnE3Yq5Q',
    appId: '1:691206438005:ios:7c7120db8199d871350c3c',
    messagingSenderId: '691206438005',
    projectId: 'readora',
    storageBucket: 'readora.appspot.com',
    iosBundleId: 'com.example.readora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCurgzkegga07FFVVJ3uuTVXvrPnE3Yq5Q',
    appId: '1:691206438005:ios:7c7120db8199d871350c3c',
    messagingSenderId: '691206438005',
    projectId: 'readora',
    storageBucket: 'readora.appspot.com',
    iosBundleId: 'com.example.readora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkNtiVS7wIY6tvhlOa4SoO_srqqBAsu6c',
    appId: '1:691206438005:web:7558a4e18b20827a350c3c',
    messagingSenderId: '691206438005',
    projectId: 'readora',
    authDomain: 'readora.firebaseapp.com',
    storageBucket: 'readora.appspot.com',
    measurementId: 'G-QP1J36KRZG',
  );
}
