import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:readora/utils/custom_snackbar.dart';

class DatabaseSeeder {
  static Future<void> seedBooks() async {
    final FirebaseFirestore firestore = FirebaseFirestore.instance;
    final userId = FirebaseAuth.instance.currentUser?.uid ?? 'admin_seeder';

    List<Map<String, dynamic>> books = [
      // Verified Working Links
      {
        'title': 'The Great Gatsby',
        'author': 'F. Scott Fitzgerald',
        'desc': 'A classic tale of wealth, love, and the American Dream in the 1920s.',
        'genre': 'Romance',
        'rating': 4.5,
        'totalratings': 1200,
        'pages': 180,
        'isbn': '9780743273565',
        'bookformat': 'Hardcover',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/81af+S9635L.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://pressbooks.library.torontomu.ca/thegreatgatsby/open/download?type=pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': '1984',
        'author': 'George Orwell',
        'desc': 'A dystopian novel about totalitarianism and surveillance.',
        'genre': 'Fantasy',
        'rating': 4.9,
        'totalratings': 8000,
        'pages': 328,
        'isbn': '9780451524935',
        'bookformat': 'Mass Market',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/1984.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Pride and Prejudice',
        'author': 'Jane Austen',
        'desc': 'A classic romantic novel dealing with manners and marriage.',
        'genre': 'Romance',
        'rating': 4.8,
        'totalratings': 4200,
        'pages': 432,
        'isbn': '9780141439518',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/71Q1Iu4suAL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/pride-and-prejudice.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'The Art of War',
        'author': 'Sun Tzu',
        'desc': 'An ancient Chinese military treatise.',
        'genre': 'History',
        'rating': 4.7,
        'totalratings': 5200,
        'pages': 100,
        'isbn': '9781590300541',
        'bookformat': 'Hardcover',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/71pU+G0jC+L.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/the-art-of-war.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Alice in Wonderland',
        'author': 'Lewis Carroll',
        'desc': 'A young girl falls through a rabbit hole.',
        'genre': 'Fantasy',
        'rating': 4.8,
        'totalratings': 4500,
        'pages': 200,
        'isbn': '9780141439761',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91pM9GjO-ML.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/alices-adventures-in-wonderland.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Sherlock Holmes',
        'author': 'Arthur Conan Doyle',
        'desc': 'The adventures of the famous detective.',
        'genre': 'Mystery',
        'rating': 4.8,
        'totalratings': 3500,
        'pages': 300,
        'isbn': '9780140439083',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/81+f4oF+X4L.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/the-adventures-of-sherlock-holmes.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Jane Eyre',
        'author': 'Charlotte Brontë',
        'desc': 'A classic novel of romance and mystery.',
        'genre': 'Romance',
        'rating': 4.6,
        'totalratings': 2800,
        'pages': 500,
        'isbn': '9780141441146',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91zXv7A+JXL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/jane-eyre.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Wuthering Heights',
        'author': 'Emily Brontë',
        'desc': 'A tale of passion and revenge.',
        'genre': 'Romance',
        'rating': 4.4,
        'totalratings': 2500,
        'pages': 400,
        'isbn': '9780141439556',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91N+7-Wn-rL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/wuthering-heights.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Great Expectations',
        'author': 'Charles Dickens',
        'desc': 'The story of an orphan named Pip.',
        'genre': 'Drama',
        'rating': 4.5,
        'totalratings': 3100,
        'pages': 500,
        'isbn': '9780141439563',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91-p-C0m0mL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/great-expectations.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Frankenstein',
        'author': 'Mary Shelley',
        'desc': 'The tale of a scientist and his creature.',
        'genre': 'Fantasy',
        'rating': 4.7,
        'totalratings': 4000,
        'pages': 280,
        'isbn': '9780141439471',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/81X4fX366rL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/frankenstein.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Dracula',
        'author': 'Bram Stoker',
        'desc': 'The definitive vampire novel.',
        'genre': 'Fantasy',
        'rating': 4.6,
        'totalratings': 3800,
        'pages': 400,
        'isbn': '9780141439846',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91uFh-zMebL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/dracula.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'A Tale of Two Cities',
        'author': 'Charles Dickens',
        'desc': 'Set in London and Paris during the French Revolution.',
        'genre': 'Drama',
        'rating': 4.6,
        'totalratings': 3300,
        'pages': 450,
        'isbn': '9780141439600',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91M6U27-F7L.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/a-tale-of-two-cities.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Moby Dick',
        'author': 'Herman Melville',
        'desc': 'The quest for the white whale.',
        'genre': 'Adventure',
        'rating': 4.2,
        'totalratings': 2200,
        'pages': 600,
        'isbn': '9780142437247',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/81e6v2R6SCL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/moby-dick.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'The Picture of Dorian Gray',
        'author': 'Oscar Wilde',
        'desc': 'A man remains young while his portrait ages.',
        'genre': 'Drama',
        'rating': 4.7,
        'totalratings': 3600,
        'pages': 250,
        'isbn': '9780141439570',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/81VStS9AVWL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/the-picture-of-dorian-gray.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Treasure Island',
        'author': 'Robert Louis Stevenson',
        'desc': 'A tale of buccaneers and buried gold.',
        'genre': 'Adventure',
        'rating': 4.7,
        'totalratings': 2900,
        'pages': 240,
        'isbn': '9780141321004',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91pM9GjO-ML.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/treasure-island.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Crime and Punishment',
        'author': 'Fyodor Dostoevsky',
        'desc': 'A psychological drama about guilt and redemption.',
        'genre': 'Drama',
        'rating': 4.8,
        'totalratings': 4100,
        'pages': 550,
        'isbn': '9780140449136',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/71PU763N0eL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/crime-and-punishment.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'The Brothers Karamazov',
        'author': 'Fyodor Dostoevsky',
        'desc': 'A complex tale of faith, doubt, and family.',
        'genre': 'Drama',
        'rating': 4.9,
        'totalratings': 3200,
        'pages': 800,
        'isbn': '9780140449242',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91PU763N0eL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/the-brothers-karamazov.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'War and Peace',
        'author': 'Leo Tolstoy',
        'desc': 'An epic saga of Russian society.',
        'genre': 'Drama',
        'rating': 4.5,
        'totalratings': 2800,
        'pages': 1200,
        'isbn': '9780140447934',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91PU763N0eL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/war-and-peace.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Les Misérables',
        'author': 'Victor Hugo',
        'desc': 'A tale of law and grace, love and revolution.',
        'genre': 'Drama',
        'rating': 4.8,
        'totalratings': 4500,
        'pages': 1400,
        'isbn': '9780140444308',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/91PU763N0eL.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/les-miserables.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'The Metamorphosis',
        'author': 'Franz Kafka',
        'desc': 'A man wakes up as a giant insect.',
        'genre': 'Drama',
        'rating': 4.4,
        'totalratings': 2900,
        'pages': 100,
        'isbn': '9780141180649',
        'bookformat': 'Paperback',
        'img': 'https://images-na.ssl-images-amazon.com/images/I/81af+S9635L.jpg',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/the-metamorphosis.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'author': 'W3C',
        'title': 'Test PDF Document',
        'desc': 'Verification test document.',
        'rating': 5.0,
        'pages': 1,
        'isbn': 'TEST-PDF-001',
        'bookformat': 'PDF',
        'img': 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      },
    ];

    // Generate 80 more books using Planet eBook patterns for Joseph Conrad and others
    final extraTitles = [
      'Heart of Darkness', 'Lord Jim', 'Nostromo', 'The Secret Agent', 
      'Victory', 'The Shadow Line', 'Typhoon', 'Youth', 
      'The Rescue', 'The Rover', 'Suspense', 'Tales of Unrest',
      'The Age of Innocence', 'The House of Mirth', 'Ethan Frome',
      'Summer', 'The Reef', 'The Custom of the Country',
      'The Awakening', 'Bayou Folk', 'A Night in Acadie',
      'The Red Badge of Courage', 'Maggie A Girl of the Streets',
      'The Monster', 'Active Service', 'The ORuddy',
      'The Monk', 'The Castle of Otranto', 'Vathek',
      'The Romance of the Forest', 'A Sicilian Romance',
      'The Mysteries of Udolpho', 'The Italian', 'Melmoth the Wanderer',
      'Don Quixote', 'Hamlet', 'Macbeth', 'King Lear', 'Othello',
      'Romeo and Juliet', 'The Merchant of Venice', 'The Tempest',
      'Julius Caesar', 'Antony and Cleopatra', 'Coriolanus',
      'The Odyssey', 'The Iliad', 'The Republic', 'The Prince',
      'Beyond Good and Evil', 'Thus Spake Zarathustra', 'The Antichrist',
      'Ecce Homo', 'The Birth of Tragedy', 'Human All Too Human',
      'The Will to Power', 'The Gay Science', 'Daybreak',
      'The Ego and Its Own', 'The Communist Manifesto', 'Capital',
      'Socialism Utopian and Scientific', 'The State and Revolution',
      'Imperialism the Highest Stage of Capitalism', 'What Is to Be Done',
      'The Wealth of Nations', 'The Theory of Moral Sentiments',
      'Common Sense', 'The Rights of Man', 'The Age of Reason',
      'The Federalist Papers', 'The Declaration of Independence',
      'The Constitution of the United States', 'Walden', 'Civil Disobedience',
      'Leaves of Grass', 'Self-Reliance', 'Nature', 'The Oversoul'
    ];

    final List<String> availableGenres = [
      'Romance',
      'Fantasy',
      'History',
      'Mystery',
      'Drama',
      'Adventure',
      'Classic',
      'Sci-Fi',
      'Thriller',
      'Biography'
    ];

    for (var i = 0; i < extraTitles.length; i++) {
      final title = extraTitles[i];
      final slug = title.toLowerCase().replaceAll(' ', '-').replaceAll('\'', '');
      books.add({
        'title': title,
        'author': 'Classic Author',
        'desc': 'A timeless classic from the world of literature.',
        'genre': availableGenres[i % availableGenres.length],
        'rating': 4.0 + (i % 10) / 10,
        'totalratings': 100 + i * 50,
        'pages': 200 + i * 10,
        'isbn': 'EXTRA-ISBN-${100 + i}',
        'bookformat': 'Paperback',
        'img': 'https://picsum.photos/id/${i + 10}/200/300',
        'isPaid': false,
        'isApproved': true,
        'pdfUrl': 'https://www.planetebook.com/free-ebooks/$slug.pdf',
        'userId': userId,
        'timestamp': FieldValue.serverTimestamp(),
      });
    }

    try {
      int count = 0;
      for (var book in books) {
        final existing = await firestore
            .collection('books')
            .where('isbn', isEqualTo: book['isbn'])
            .get();

        if (existing.docs.isEmpty) {
          await firestore.collection('books').add(book);
        } else {
          await existing.docs.first.reference.set(book, SetOptions(merge: true));
        }
        count++;
      }
      customSnackbar(title: 'Success', message: '$count books synced successfully!');
    } catch (e) {
      customSnackbar(title: 'Error', message: 'Failed to seed books: $e');
    }
  }
}
